Update dependencies for v1 branch
kuskoman/logstash-exporter pull request #277
Opened 2024-02-15 13:09 UTC by satk0

2024-02-15 13:17 UTC, kuskoman requested changes

2024-02-15 13:17 UTC, kuskoman commented on .github/workflows/go-application.yml
> +        uses: actions/checkout@v4.1.1
don't pin the version

2024-02-15 14:19 UTC, kuskoman commented
@satk0 prometheus tests are failing

2024-02-15 22:27 UTC, kuskoman commented
@satk0 seems like the upgrade-dependencies script differs between v1 and v2
also, you may want to check this pr #280

2024-02-16 10:04 UTC, satk0 commented
@kuskoman Thanks a ton for all the hints. I am giving it another try 😎

2024-02-16 10:23 UTC, kuskoman approved these changes

2024-02-16 10:25 UTC, merged