Implement hot reload
kuskoman/logstash-exporter pull request #343
Opened 2024-07-25 11:52 UTC by satk0

2024-08-21 16:13 UTC, kuskoman commented on internal/startup_manager/startup_manager.go
> +var previousCollector prometheus.Collector = nil
isn't nil the default for it?

2024-08-21 16:13 UTC, kuskoman commented on internal/startup_manager/startup_manager.go
> +		slog.Info("Config reloaded")
logs should start from lowercased letters

2024-08-21 16:13 UTC, kuskoman commented on internal/startup_manager/startup_manager.go
> +		slog.Info("Prometeus reloaded")
logs should start from lowercased letters

2024-08-21 16:14 UTC, kuskoman commented on internal/startup_manager/startup_manager.go
> +	reloadManager.On(reload.NotifierFunc(func(ctx context.Context) (string, error) {
if the file gets written, but no config gets changed this still reloads the server, right? it may not be the best approach

2024-08-26 17:59 UTC, satk0 commented on internal/startup_manager/startup_manager.go
> +	reloadManager.On(reload.NotifierFunc(func(ctx context.Context) (string, error) {
Yeah, that's right. I made it like that because Neovim's file-saving is a nightmare. If I manage to somehow avoid it triggering when no config is changed, would u accept it?

2024-09-04 13:30 UTC, kuskoman commented on internal/startup_manager/startup_manager.go
> +var previousCollector prometheus.Collector = nil
bump for this comment

2024-09-04 13:33 UTC, kuskoman commented on internal/startup_manager/startup_manager.go
> +		if (id == "no-event") {
don't use magic string, use const for that
and since it is repeated make function isNothingChanged or similar

2024-09-04 13:34 UTC, kuskoman commented on internal/startup_manager/startup_manager.go
> +	reloadManager.On(reload.NotifierFunc(func(ctx context.Context) (string, error) {
yes
but you should parse it first
so
- file was written with the same content- ignore it
- file was written with different content, but the struct with config was not changed (eg. order was changed, whitespace was added)
you should ignore that

2024-09-04 13:35 UTC, kuskoman commented on internal/startup_manager/startup_manager.go
> +				return "no-event", err
same, assign to const

2024-09-04 13:36 UTC, kuskoman commented
seems like some conflicts appeared, could you try to resolve them as well?

2024-09-04 13:40 UTC, satk0 commented
Sure, you are speeeed

2024-09-04 16:21 UTC, satk0 commented
chck it jetzt Bruder

2024-09-04 18:04 UTC, kuskoman commented
i need to check it locally, will do that later on

2024-09-09 10:47 UTC, kuskoman commented
@satk0 I tested it and it is not working properly, it reloads the prometheus server even if file is written with exactly the same content. furthermore, you should add a check that will parse the config before reloading it and compare to the current config, to see if something was changed

2024-09-09 16:42 UTC, satk0 commented
Allright, Thanks a lot for checking it, such a parse-before-reloading feature would solve the problem. I will fix it after I will get it to build on NixOS, cuz I've once switched my os to nix XD

2024-09-17 09:33 UTC, satk0 commented
@kuskoman Done.

2024-09-23 18:13 UTC, kuskoman requested changes

2024-09-23 18:13 UTC, kuskoman commented on internal/startup_manager/flags.go
> +	hotReloadFlag := flag.Bool("hot-reload", false, "enable configuration hot reload")
i would like to shorten this flag to something like -watch

2024-09-23 18:13 UTC, kuskoman commented on internal/startup_manager/startup_manager.go
> +	// hot reload:
remove comment

2024-09-23 18:13 UTC, kuskoman commented on internal/startup_manager/startup_manager.go
> +	// Prometheus reloader
if you need a comment, you need to extract the logic to a separate function :D

2024-09-23 18:13 UTC, kuskoman commented on internal/startup_manager/startup_manager.go
> +				if !ok {
a lot of nested structures, the code is not readable enough

2024-09-25 19:25 UTC, satk0 commented on internal/startup_manager/startup_manager.go
> +				if !ok {
Would putting `if strings.Contains(event.Name, fname) { ,,, }` in a new function named `sendConfigUpdatedEvent` do?

2024-09-27 17:10 UTC, satk0 commented
Done, lemme know how it looks @kuskoman

2024-09-30 17:58 UTC, kuskoman commented on internal/startup_manager/startup_manager.go
> +				if !ok {
i think so, generally try to split it into smaller function and consider not using anonymous func there

2024-10-03 11:59 UTC, jshemfrid approved these changes

2024-10-03 12:03 UTC, kuskoman approved these changes

2024-10-03 12:03 UTC, merged